---
- name: Debug GitHub runner token
  hosts: localhost
  gather_facts: no
  vars:
    ansible_connection: local
  tasks:
    - name: Toon de inhoud van github_runner_token
      debug:
        var: github_runner_token

    - name: Show all hosts
      debug:
        var: groups['all']

    - name: Show all vars for localhost
      debug:
        var: hostvars['localhost']