name: Deploy to K3s (dev and prod)

on:
  push:
    branches: [main]
    paths:
      - "k8s/dev/**"
      - "k8s/prod/**"

jobs:
  deploy-dev:
    name: Deploy to Dev
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to K3s (dev namespace)
        run: |
          kubectl apply -f k8s/dev/nginx-deployment.yml -n dev
          kubectl apply -f k8s/dev/nginx-service.yml -n dev

  wait-for-approval:
    name: Wait for manual approval
    runs-on: ubuntu-latest
    needs: deploy-dev
    steps:
      - name: Wait for approval
        uses: hmarr/auto-approve-action@v3
        if: github.event_name == 'workflow_dispatch'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  deploy-prod:
    name: Deploy to Prod
    runs-on: self-hosted
    needs: deploy-to-dev # wacht tot dev-deploy klaar is
    environment:
      name: production # activeert handmatige goedkeuring via GitHub UI
      url: http://prod.example.com
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to K3s (prod namespace)
        run: |
          export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
          kubectl apply -f k8s/prod/nginx-deployment.yml -n prod
          kubectl apply -f k8s/prod/nginx-service.yml -n prod
