name: Ansible Deploy to Localhost

on:
  push:
    branches:
      - main
    paths:
      - "playbooks/**"
      - "inventory/**"
      - ".github/workflows/deploy_ansible1.yml"

jobs:
  deploy:
    runs-on: self-hosted
    name: Run Ansible Playbook on Localhost

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Ansible Playbook
        run: |
          ansible-playbook playbooks/install_tools.yml --inventory inventory/localhost --become --become-user=root
