name: Deploy to K3s (dev and prod)

on:
  push:
    branches: [main]
    paths:
      - "k8s/dev/**"
      - "k8s/prod/**"

jobs:
  deploy-dev:
    name: Deploy to Dev
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to K3s (dev namespace)
        run: |
          kubectl apply -f k8s/dev/nginx-deployment.yml -n dev
          kubectl apply -f k8s/dev/nginx-service.yml -n dev

  deploy-prod:
    name: Deploy to Prod
    runs-on: self-hosted
    needs: deploy-dev # corrected here
    environment:
      name: production # GitHub maakt hier een handmatige goedkeuring voor aan
      url: http://prod.example.com
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to K3s (prod namespace)
        run: |
          export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
          kubectl apply -f k8s/prod/nginx-deployment.yml -n prod
          kubectl apply -f k8s/prod/nginx-service.yml -n prod
